### ISSUE TITLE
Question: Why does Optimizely plugin get called for each `track` call?

### ISSUE THREAD

**Issue by skydivedan** [segment-integrations/analytics-swift-optimizely#9]
Hi there,

First, allow me to say that I may just completely misunderstand how things work with Segment destinations. So, this question may come from a place of ignorance. But pressing on...

Why does `OptimizelyFullStack` call the iOS Optimizely plugin itself? 

My understanding of `DestinationPlugin` is that the plugin is given an opportunity to modify the `TrackEvent` (for example) by passing back a different `TrackEvent` than what was passed in (usually by making a copy of the original, and adding new properties to it). Then, that modified `TrackEvent` gets sent to the `Segment` service online, and then that event is sent to the `Optimizely` destination. If that's true, then why would we need to call the iOS Client's `Optimizely` library here?

Just curious. Not trying to criticize the choice here, just trying to fill in my understanding.

**Comment by alanjcharles** [comment]
Hi @skydivedan Thanks for reaching out, no worries at all. 

The flow you are describing is correct for `Destination Actions`. The only one that the mobile libraries support is `Amplitude Actions`.  Unless otherwise stated, `Destination Plugins` in `Analytics-Swift` are the equivalent of a `Device-Mode` destination. 

**Destination Plugins**
A Destination Plugin includes the given destination's SDK as a dependency. When an event is invoked in the Segment SDK we map a copy of the event to the partner-SDK's event structure the best we can but ultimately it is the partner-SDK that sends the event directly from the device to their own endpoints (ie these do not get sent from Segment's servers). This means you also have access to all of the partner-SDK functionality you would otherwise have if you were using it as a standalone product. 

**Choosing a Connection Mode**

You'll notice some destinations offer both Cloud and Device Mode connections (ie Mixpanel), while some only have one or the other (ie Firebase). If a given destination has both options, your choice depends on what you need. If you _just_ need data collected by Segment then you would want to choose a Cloud Mode connection. If you need additional information that is not collected by Segment but is collected by a destination's stand-alone SDK, you would would choose a Device Mode connection. 

In cases where we only offer a Device Mode connection it is typically because the partner does not have an accessible API we can hit from our server's, or because it simply can't function as would be expected if the SDK isn't included (ie Firebase). 

I have included a [link to our docs](https://segment.com/docs/connections/destinations/#connection-modes) here if you would like to read about this further. I hope this helps! Feel free to re-open if you have any other questions.
